# -*- coding: utf-8 -*-
"""gigamaps_connectivity_status.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11s4FMDoeDJCgvf2QC224TwuxeKTeEBUm

1. Step 1 - connectivity status
"""

# this code below works
import requests
import pandas as pd
import time

# ---------------------------------------------------------------
# 1. CONFIGURATION
# ---------------------------------------------------------------
API_KEY     = ""   # <-- paste your real token here
BASE_URL    = "https://uni-ooi-giga-maps-service.azurewebsites.net/api/v1/schools_profile/"
PAGE_SIZE   = 1000
TIMEOUT     = 60
MAX_RETRIES = 3

HEADERS = {"Authorization": f"Bearer {API_KEY}", "Accept": "application/json"}

COUNTRIES = {
    "BWA": "Botswana",
    "GMB": "Gambia",
    "GIN": "Guinea",
    "LSO": "Lesotho",
    "MWI": "Malawi",
    "NAM": "Namibia",
    "NER": "Niger",
    "SLE": "Sierra Leone",
    "ZAF": "South Africa",
    "SSD": "South Sudan",
    "TZA": "United Republic of Tanzania",
    "ZWE": "Zimbabwe",
}

# ---------------------------------------------------------------
# 2. NORMALIZE THE RESPONSE INTO A LIST OF DICTS
# ---------------------------------------------------------------
def extract_records(payload):
    """The API returns {'success': ..., 'data': [...]}. Pull out 'data'
    as a list of dict records; tolerate other shapes just in case."""
    if isinstance(payload, dict):
        records = payload.get("data")
        if not isinstance(records, list):
            # fall back to first list-valued field
            lists = [v for v in payload.values() if isinstance(v, list)]
            records = lists[0] if lists else []
    elif isinstance(payload, list):
        records = payload
    else:
        records = []
    return [row for row in records if isinstance(row, dict)]

# ---------------------------------------------------------------
# 3. FETCH ONE PAGE (with retries)
# ---------------------------------------------------------------
def fetch_page(iso3, page, size):
    params = {"country_iso3_code": iso3, "page": page, "size": size}
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            r = requests.get(BASE_URL, headers=HEADERS,
                             params=params, timeout=TIMEOUT)
        except requests.exceptions.RequestException as e:
            print(f"    network error (attempt {attempt}/{MAX_RETRIES}): {e}")
            time.sleep(2 * attempt)
            continue

        if r.status_code == 200:
            payload = r.json()
            # optional guard: honor the API's own success flag
            if isinstance(payload, dict) and payload.get("success") is False:
                print(f"    API reported success=False on page {page}")
                return [], True
            return extract_records(payload), True
        if r.status_code == 404:
            return [], True
        if r.status_code in (401, 403):
            print(f"    auth error {r.status_code}: check your API_KEY")
            return [], False
        if 500 <= r.status_code < 600:
            print(f"    server error {r.status_code} (attempt {attempt}); retrying")
            time.sleep(2 * attempt)
            continue

        print(f"    unexpected {r.status_code}: {r.text[:200]}")
        return [], False

    print("    gave up after retries")
    return [], False

# ---------------------------------------------------------------
# 4. MAIN LOOP
# ---------------------------------------------------------------
all_data = []
for iso3, country in COUNTRIES.items():
    print(f"\nDownloading {country} ({iso3})")
    page, total = 1, 0
    while True:
        data, ok = fetch_page(iso3, page, PAGE_SIZE)
        if not ok:
            break
        if len(data) == 0:
            break

        for row in data:
            row["country_name"] = country
        all_data.extend(data)

        total += len(data)
        print(f"  page {page}: {len(data)} records")

        if len(data) < PAGE_SIZE:
            break
        page += 1
        time.sleep(0.2)
    print(f"  Total for {country}: {total}")

# ---------------------------------------------------------------
# 5. ASSEMBLE
# ---------------------------------------------------------------
df = pd.DataFrame(all_data)
print(f"\nFinished. Combined shape: {df.shape}")
df.head()

df.to_csv('/content/drive/MyDrive/Digital/gigamaps/giga.csv')